---
trust-domain: ci
treeherder:
    group-names:
        'I': 'Docker Image Builds'

task-priority: low

taskgraph: {}

workers:
    aliases:
        images:
            provisioner: aws-provisioner-v1
            implementation: docker-worker
            os: linux
            worker-type: 'gecko-{level}-{alias}'
        misc:
            provisioner: aws-provisioner-v1
            implementation: docker-worker
            os: linux
            worker-type: 'gecko-{alias}'
